package com.insaj.entidades;
// Generated Apr 19, 2017 9:28:25 PM by Hibernate Tools 4.3.1



/**
 * Detalledocentematerias generated by hbm2java
 */
public class Detalledocentematerias  implements java.io.Serializable {


     private DetalledocentemateriasId id;

    public Detalledocentematerias() {
    }

    public Detalledocentematerias(DetalledocentemateriasId id) {
       this.id = id;
    }
   
    public DetalledocentemateriasId getId() {
        return this.id;
    }
    
    public void setId(DetalledocentemateriasId id) {
        this.id = id;
    }




}


