package com.insaj.entidades;
// Generated Apr 19, 2017 9:28:25 PM by Hibernate Tools 4.3.1



/**
 * DetalledocentemateriasId generated by hbm2java
 */
public class DetalledocentemateriasId  implements java.io.Serializable {


     private int idMateria;
     private int idDocente;

    public DetalledocentemateriasId() {
    }

    public DetalledocentemateriasId(int idMateria, int idDocente) {
       this.idMateria = idMateria;
       this.idDocente = idDocente;
    }
   
    public int getIdMateria() {
        return this.idMateria;
    }
    
    public void setIdMateria(int idMateria) {
        this.idMateria = idMateria;
    }
    public int getIdDocente() {
        return this.idDocente;
    }
    
    public void setIdDocente(int idDocente) {
        this.idDocente = idDocente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalledocentemateriasId) ) return false;
		 DetalledocentemateriasId castOther = ( DetalledocentemateriasId ) other; 
         
		 return (this.getIdMateria()==castOther.getIdMateria())
 && (this.getIdDocente()==castOther.getIdDocente());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdMateria();
         result = 37 * result + this.getIdDocente();
         return result;
   }   


}


