package com.insaj.entidades;
// Generated Apr 19, 2017 9:28:25 PM by Hibernate Tools 4.3.1



/**
 * DetallehorarioId generated by hbm2java
 */
public class DetallehorarioId  implements java.io.Serializable {


     private Integer idHorario;
     private Integer idClase;

    public DetallehorarioId() {
    }

    public DetallehorarioId(Integer idHorario, Integer idClases) {
       this.idHorario = idHorario;
       this.idClase = idClases;
    }
   
    public Integer getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(Integer idHorario) {
        this.idHorario = idHorario;
    }

    public Integer getIdClase() {
        return idClase;
    }

    public void setIdClase(Integer idClase) {
        this.idClase = idClase;
    }
   




}


