package com.insaj.entidades;
// Generated Apr 19, 2017 9:28:25 PM by Hibernate Tools 4.3.1



/**
 * Detallehorario generated by hbm2java
 */
public class Detallehorario  implements java.io.Serializable {


     private DetallehorarioId id;
     private Clases clases;
     private Horarios horarios;

    public Detallehorario() {
    }

	
    public Detallehorario(DetallehorarioId id) {
        this.id = id;
    }
    public Detallehorario(DetallehorarioId id, Clases clases, Horarios horarios) {
       this.id = id;
       this.clases = clases;
       this.horarios = horarios;
    }
   
    public DetallehorarioId getId() {
        return this.id;
    }
    
    public void setId(DetallehorarioId id) {
        this.id = id;
    }
    public Clases getClases() {
        return this.clases;
    }
    
    public void setClases(Clases clases) {
        this.clases = clases;
    }
    public Horarios getHorarios() {
        return this.horarios;
    }
    
    public void setHorarios(Horarios horarios) {
        this.horarios = horarios;
    }




}


