package com.insaj.entidades;
// Generated Apr 19, 2017 9:28:25 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Materias generated by hbm2java
 */
public class Materias  implements java.io.Serializable {


     private Integer idMateria;
     private String nombre;
     private String tipo;
     private Set<Docentes> Docentes=new HashSet<Docentes>();
     private Set<Secciones> Secciones = new HashSet();

    public Materias() {
    }

    public Materias(Integer idMateria, String nombre, String tipo) {
        this.idMateria = idMateria;
        this.nombre = nombre;
        this.tipo = tipo;
    }

	
    public Materias(String nombre, String tipo) {
        this.nombre = nombre;
        this.tipo = tipo;
    }
    public Materias(String nombre, String tipo, Set materiasporseccions) {
       this.nombre = nombre;
       this.tipo = tipo;
       this.Secciones = materiasporseccions;
    }
   
    public Integer getIdMateria() {
        return this.idMateria;
    }
    
    public void setIdMateria(Integer idMateria) {
        this.idMateria = idMateria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getMateriasporseccions() {
        return this.Secciones;
    }
    
    public void setMateriasporseccions(Set materiasporseccions) {
        this.Secciones = materiasporseccions;
    }

    public Set<Docentes> getDocentes() {
        return Docentes;
    }

    public void setDocentes(Set<Docentes> Docentes) {
        this.Docentes = Docentes;
    }

    public Set<Secciones> getSecciones() {
        return Secciones;
    }

    public void setSecciones(Set<Secciones> Secciones) {
        this.Secciones = Secciones;
    }
    public List<Docentes> getDocentesList(){
        List<Docentes> l = new ArrayList<>(Docentes);
       return l;
    }
 @Override
    public String toString(){
     return this.nombre;
    }


}


