package com.insaj.entidades;
// Generated Apr 19, 2017 9:28:25 PM by Hibernate Tools 4.3.1



/**
 * Materiasporseccion generated by hbm2java
 */
public class Materiasporseccion  implements java.io.Serializable {


     private MateriasporseccionId id;
     private Materias materias;
     private Secciones secciones;

    public Materiasporseccion() {
    }

    public Materiasporseccion(MateriasporseccionId id, Materias materias, Secciones secciones) {
       this.id = id;
       this.materias = materias;
       this.secciones = secciones;
    }
   
    public MateriasporseccionId getId() {
        return this.id;
    }
    
    public void setId(MateriasporseccionId id) {
        this.id = id;
    }
    public Materias getMaterias() {
        return this.materias;
    }
    
    public void setMaterias(Materias materias) {
        this.materias = materias;
    }
    public Secciones getSecciones() {
        return this.secciones;
    }
    
    public void setSecciones(Secciones secciones) {
        this.secciones = secciones;
    }




}


