package com.insaj.entidades;
// Generated Apr 19, 2017 9:28:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer idUsuario;
     private Roles roles;
     private String usuario;
     private String password;
     private String nombre;
     private Set horarioses = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(Roles roles) {
        this.roles = roles;
    }
    public Usuarios(Roles roles, String usuario, String password, String nombre) {
       this.roles = roles;
       this.usuario = usuario;
       this.password = password;
       this.nombre = nombre;
    }

    public Usuarios(Integer idUsuario, Roles roles, String usuario, String password, String nombre) {
        this.idUsuario = idUsuario;
        this.roles = roles;
        this.usuario = usuario;
        this.password = password;
        this.nombre = nombre;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getHorarioses() {
        return this.horarioses;
    }
    
    public void setHorarioses(Set horarioses) {
        this.horarioses = horarioses;
    }




}


